# This is a basic workflow to help you get started with Actions

name: Render & Deploy Site

on:

  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master
      
      - name: Install Dependencies
        
        run: |
          install.packages("renv")
          renv::restore()
        shell: Rscript {0}


      - name: Render Site
        run: rmarkdown::render_site(encoding = "UTF-8")
        shell: Rscript {0}

      - name: Commit results
        run: |
          git add -A
          git commit -m 'Rebuild site' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
